<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ9iWrYV\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ9iWrYV/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJ9iWrYV.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJ9iWrYV\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJ9iWrYV\App_KernelProdContainer([
    'container.build_hash' => 'J9iWrYV',
    'container.build_id' => '96bd7983',
    'container.build_time' => 1756204359,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ9iWrYV');
